### ISSUE TITLE
Collaboration Opportunity: VerticaPy and BigFrame

### ISSUE THREAD

**Issue by oualib** [googleapis/python-bigquery-dataframes#24]
Dear Google BigFrame Team,

I hope this message finds you well. I am writing to discuss a potential collaboration opportunity that could greatly benefit both the BigFrame project and the data science community as a whole.

VerticaPy, a mature and production-tested project that has been in development for over 5 years, offers a wide range of data science functionalities with seamless integration. Its robust "vDataFrame" object has proven its effectiveness with numerous features.

One of the notable advantages of VerticaPy is its generation of standard SQL for many functions, making it a strong candidate for seamless integration with BigQuery.

I believe that a collaboration between the BigFrame project and VerticaPy could lead to significant improvements in the field of Big Data. I am more than willing to provide a demonstration of VerticaPy's capabilities and explore how we can work together to make data science more accessible for Big Data applications.

We have a deep understanding of the market and are eager to contribute to the success of both projects.

Please let me know if you would be interested in exploring this collaboration further. I am available for a discussion at your convenience.

Link to the VerticaPy GitHub: https://github.com/vertica/VerticaPy

Link to the VerticaPy website: https://www.vertica.com/python/

You can contact me at: bouali@opentext.com

Thank you for considering this proposal, and I look forward to your response.

Sincerely,

Badr Ouali

**Comment by tswast** [comment]
Thanks for the feedback! This does look like an interesting project with similar goals. I'd be interested in hearing some more details for potential collaboration?
