### ISSUE TITLE
Notebook rendering error on GitHub

### ISSUE THREAD

**Issue by pkubik** [googleapis/python-bigquery-dataframes#707]
It seems like the the notebook examples are not rendered correctly. Probably some nbconvert compatibility issues.

```
An error occurred

<space warrior octocat image>

Using nbformat v5.10.4 and nbconvert v7.16.1
```

![image](https://github.com/googleapis/python-bigquery-dataframes/assets/4431772/6f2cc7cb-3170-4fc2-8f9b-3dcda6d0972b)

Occurs for all notebook examples, e.g.
https://github.com/googleapis/python-bigquery-dataframes/blob/main/notebooks/getting_started/getting_started_bq_dataframes.ipynb

I tested on the latest Chrome and Edge browsers

```
Chrome 124.0.6367.208 (Official Build) (arm64)
Edge 123.0.2420.97 (Official build) (arm64)
```

I guess the notebooks needs to be re-rendered with newer jupyter tools?

**Comment by tswast** [comment]
Thanks for the heads up! I can see if we can run a notebook formatter/linter as part of our check-in process.

**Comment by tswast** [comment]
I wonder if this was a temporary GitHub problem? It looks like it's rendering okay to me:

<img width="1601" alt="Screenshot 2024-05-22 at 9 30 55 AM" src="https://github.com/googleapis/python-bigquery-dataframes/assets/247555/b1f40127-9097-4318-a7db-b0154370273d">

That said, might be worth keeping this open to track rendering the notebooks somewhere in the cloud.google.com/bigquery/docs to have a workaround for these problems in future.

**Comment by pkubik** [comment]
It works now. Seems like a temporary error indeed.
